---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-ssl
  namespace: loki-stack
spec:
  isCA: true
  commonName: loki-grafana
  secretName: loki-ssl
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io